/**
 * Home's Suggest prompt: one project idea at a time, put in the composer for someone who does not
 * know where to start. Each is one sentence a person might type, small enough to build tonight.
 */

/** The ideas Suggest prompt draws from. */
export const PROMPT_IDEAS = [
  "A habit tracker with a streak calendar and a gentle weekly review",
  "A kanban board for a family with chores that move across the columns",
  "A recipe box that scales ingredients and builds a shopping list",
  "A personal budget dashboard with monthly categories and a savings goal",
  "A markdown notes app with tags, search and a split preview",
  "A pomodoro timer that logs focus sessions and charts the week",
  "A flashcard trainer with spaced repetition and a daily queue",
  "A bookshelf tracker with reading progress and a year-in-review page",
  "A tiny CRM for freelancers with clients, invoices and follow-up reminders",
  "A trip planner with a day-by-day itinerary and a packing checklist",
  "A workout log that charts personal records by exercise",
  "A meal planner with a weekly grid and a nutrition summary",
  "A color palette generator with contrast checks and export to CSS variables",
  "A JSON formatter and diff viewer that runs entirely in the browser",
  "A unit converter with live results and a history of recent conversions",
  "A markdown resume builder with three printable templates",
  "A landing page for a local bakery with a menu, hours and an order form",
  "A portfolio site for a photographer with a filterable gallery and a lightbox",
  "A documentation site with a sidebar, search and copyable code samples",
  "A changelog page that groups releases by month with filters for type",
  "A restaurant reservation form with party size, time slots and validation",
  "A multi-step signup flow that remembers progress and explains every error",
  "A feedback survey with conditional questions and a results summary",
  "A support ticket inbox with filters, assignment and a status timeline",
  "An invoice generator with line items, taxes and a print-ready layout",
  "A team standup board where everyone posts yesterday, today and blockers",
  "A sales dashboard with revenue trends, top products and a region map",
  "A website analytics dashboard with visitors, sources and a live feed",
  "A server status page with uptime bars and incident history",
  "A project timeline with draggable milestones and dependency lines",
  "A mind map editor with keyboard shortcuts and an outline view",
  "A diagram editor with draggable nodes, connectors and snap to grid",
  "A spreadsheet-like table with formulas, sorting and column resizing",
  "A drawing board with layers, undo and export to PNG",
  "A code snippet manager with languages, tags and instant search",
  "A password generator with strength meter and copy-to-clipboard",
  "A regex tester with live matches, groups and an explanation panel",
  "A cron expression builder that explains the schedule in plain words",
  "A markdown to slides converter with speaker notes and a presenter view",
  "A kanban for job applications with stages, notes and interview dates",
  "A language learning dashboard with vocabulary lists and a daily goal",
  "A plant care tracker with watering reminders and a photo journal",
  "A home inventory with rooms, receipts and warranty expiry alerts",
  "A car maintenance log with service history and upcoming reminders",
  "A podcast player with episode queue, speed control and resume position",
  "A music practice tracker with metronome, goals and weekly stats",
  "A voting app for choosing a restaurant with a group and live results",
  "An expense splitter for a trip with balances and who-owes-whom",
  "A gift list manager with budgets, links and a surprise-safe sharing view",
  "A wedding planning dashboard with guests, seating and a budget",
  "An event schedule app for a conference with tracks, talks and favorites",
  "A classroom gradebook with weighted categories and a student progress view",
  "A quiz builder with timers, scoring and a shareable results page",
  "A typing speed trainer with lessons, accuracy stats and a progress chart",
  "A color-blind friendly chart builder from pasted CSV data",
  "A CSV explorer with column stats, filters and quick charts",
  "A data table with virtual scrolling for fifty thousand rows",
  "A pull request reviewer with a side-by-side diff and inline comments",
  "A color contrast checker for design teams with a shareable report",
  "A design token viewer that previews spacing, type and color scales",
  "A component gallery with live props, dark mode and accessibility notes",
  "A style guide for a small brand with logos, colors and usage rules",
  "A sticky notes wall with drag, resize and color tags",
  "A countdown page for a launch with a newsletter signup",
  "A link-in-bio page with analytics for each button",
  "A pricing page with a monthly and yearly toggle and a feature comparison",
  "A checkout flow with a cart, shipping options and a clear order summary",
  "A product catalogue with faceted filters, sorting and a compare drawer",
  "A wishlist app that tracks price drops across saved links",
  "A booking calendar for a hair salon with services and available slots",
  "A volunteer sign-up sheet with shifts, capacity and reminders",
  "A neighborhood tool library with availability and a borrow history",
  "A potluck planner where guests claim dishes and avoid duplicates",
  "A time zone planner that finds a meeting hour for a remote team",
  "A journal app with mood tracking and a monthly reflection chart",
  "A medication reminder with a daily schedule and a refill alert",
  "A sleep tracker with a weekly chart and a bedtime consistency score",
  "A water and coffee intake logger with a friendly daily summary",
  "A package tracker dashboard with status steps and delivery estimates",
  "A flight itinerary organizer that merges bookings into one timeline",
  "A hiking route planner with elevation profile and a gear checklist",
  "A star chart that shows what is above you tonight",
  "A tide and weather planner for sailors with a go or no-go summary",
  "A chess opening trainer with a move tree and spaced review",
  "A sudoku helper with candidate notes and hint explanations",
  "A word game helper that suggests plays from a rack of letters",
  "A crossword builder with a grid editor and clue list",
  "A trivia night host console with rounds, scores and a projector view",
  "A raffle and name picker with a spinning reveal and a fair history",
  "A text diff tool with word-level highlighting and an unlimited undo",
  "A bulk file renamer preview with rules, patterns and a safe undo",
  "A color picker that extracts a palette from an uploaded photo",
  "A QR code generator with a style editor and downloadable SVG",
  "A tiny wiki with backlinks, a graph view and a page history",
  "An API explorer that sends requests, shows responses and saves collections",
  "A log viewer with filters, highlighting and a live tail",
  "A feature flag dashboard with environments, rollouts and an audit log",
  "A release checklist that tracks owners, status and a go-live countdown",
  "An onboarding checklist for new hires with progress and a welcome page",
  "An accessibility audit tracker with issue severity and a fix status board",
] as const;

/** A random idea from the list, never the one just shown. */
export function pickPromptIdea(previous: string | null, random: () => number = Math.random): string {
  const others = PROMPT_IDEAS.filter((idea) => idea !== previous);
  return others[Math.floor(random() * others.length)] ?? PROMPT_IDEAS[0];
}
